name: "CI/CD pull request"

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  check-version:
    name: "Check version"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Run Version Check
        run: ./scripts/validate-version-to-latest-tag.sh modules/aws-backup-source/version
